# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  repository_dispatch:
     type: [github_actions]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: mvn -B package --file spring3hibernate/pom.xml
    
    - name: running command to cat team1.tf file
      run: cat team1.tf
    
    - name: running command to add module team1.tf file
      run: ./script.sh team1 new_one

    - name: running command to cat team1.tf file
      run: cat team1.tf

    - name: Now team2
      run: echo "Now Team-2"

    - name: running command to cat team2.tf file
      run: cat team2.tf
    
    - name: running command to add module team2.tf file
      run: ./script.sh team2 new_one

    - name: running command to cat team2.tf file
      run: cat team2.tf

